
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: survey_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: survey_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: survey_production
  username: associations_part_1
  password: <%= ENV["SURVEY_DATABASE_PASSWORD"] %>
